# Numpy Operations

In [1]:
import numpy as np


In [2]:
arr1 = np.arange(11)

In [3]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr2 = np.arange(12, 23)

In [7]:
arr2

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

## Arithmatic Operations

### 1. Addition
    Each element of 1st array get added with 2nd array

In [8]:
arr1 + arr2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

### 2. Subtraction

In [10]:
arr2 - arr1

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

### 3. Multiplication

In [11]:
arr1 * arr2

array([  0,  13,  28,  45,  64,  85, 108, 133, 160, 189, 220])

## Scalar Operation

In [12]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr1 * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [14]:
arr1+20

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

Numpy will give an warning while dividing by `zero` and replace the value with `nan`

In [15]:
arr1/0

C:\Users\DELL\AppData\Local\Temp\ipykernel_12532\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0
C:\Users\DELL\AppData\Local\Temp\ipykernel_12532\1510032488.py:1: RuntimeWarning: invalid value encountered in divide
  arr1/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

`inf` stands for `infinity`.

In [16]:
arr1 = np.arange(11)

In [17]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Universal Array function

#### 1. sqrt()

In [18]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

#### 2. exp()
    this is exponential.

np.exp(arr1)

#### 3. max() & min()

In [20]:
arr1.max()

10

In [21]:
arr1.min()

0

#### 4. logrithmic

In [22]:
np.log(arr1)

C:\Users\DELL\AppData\Local\Temp\ipykernel_12532\2108464003.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

#### 5. Triginometric

In [23]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [24]:
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])