# NumPy Array


#### <p style="color: green">Converting Python list to an Array.</p>

In [4]:
my_list = [1,2,3]

In [5]:
import numpy as np


In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

##### Creating 2-D array from list of list

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## np.arange() function
* works similar to range function.
* Syntax:
    * `np.arange(initial_point, final_point(excluded), steps)`

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

## Array of Zeros and Ones

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace() function
* `linspace()` funtion returns evenly spaced numbers over a specified interval.
* Syntax:    
  * `numpy.linspace(start, stop, num=(default)=0)`


In [17]:
np.linspace(0,10, 3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,15,3)

array([ 0. ,  7.5, 15. ])

In [21]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye() 
* this function is used to create Identity matrix.
* It takes only single integer argument.

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random
    we can create array with random numbers with the help of numpy's random functon.

### 1. rand
* Create an array of given size, and populate the array with random samples from `unifrom` distribution between [0,1).
* Can be used to create both 1-D and 2-D array.

In [23]:
np.random.rand(5)

array([0.2873602 , 0.40150151, 0.70171158, 0.86044765, 0.19460924])

In [24]:
np.random.rand(5,5)

array([[0.04896979, 0.40945072, 0.70288613, 0.139029  , 0.61867426],
       [0.42880156, 0.74462005, 0.08363024, 0.53111993, 0.79914373],
       [0.08293428, 0.92356993, 0.35235041, 0.73213756, 0.2290978 ],
       [0.9967131 , 0.72063363, 0.73922922, 0.10824931, 0.90352201],
       [0.31139896, 0.95128477, 0.59672523, 0.79277694, 0.14682039]])

### 2. randn
* Create an array of given size, and populate the array with random samples from `Normal` distribution.
* Can be used to create both 1-D and 2-D array.

In [26]:
np.random.randn(3)

array([-0.46685908,  0.55281985,  2.25903408])

In [27]:
np.random.randn(4,4)

array([[ 1.39542342, -0.60582664, -0.08911618,  0.3179702 ],
       [ 1.47381205, -1.38122493, -2.28482288,  0.98996248],
       [-0.79500662, -0.52362084,  0.09949904, -0.73541496],
       [ 0.89913302, -1.42312726, -0.3527272 , -0.67306674]])

### 3. randint
* Return random integers from low (inclusive) to high (exclusive).
* Syntax:
  * `randint(low, high, size(default = 1))`

In [28]:
np.random.randint(1,100)

20

In [29]:
np.random.randint(1,100,20)

array([98, 68,  9, 75, 40, 99, 85, 43, 10, 68,  1, 37, 18,  8, 63, 95, 82,
       23,  1, 74])

## Array Attributes and Methods

In [38]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50,10)

In [33]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr

array([26, 18, 16, 22,  7, 36, 26, 35,  1, 25])

### 1. reshape
* Returns an array containing the same data with a new shape.
* new shape means `1D to 2D` or `2D to 1D`.

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

* you will get an error if you try to reshape the array with incomplete elements.

In [39]:
arr.reshape(5,6)

ValueError: cannot reshape array of size 25 into shape (5,6)

* to Reshape the array into `5x6` you need to have 30 elements at the array you are trying to shape.

## 2. Max, Min
    Return the max and min value from the array.

In [40]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr.max()

24

In [42]:
arr.min()

0

## 3. argmax, argmin
    returns the index value of the max and min elements.

In [45]:
ranarr

array([ 6, 22, 19, 25, 41,  8, 48, 41, 35, 27])

In [47]:
ranarr.argmax()

6

In [48]:
ranarr.argmin()

0

## Shape
* this is a attribute not a method.
* It returns the shape of the array.

In [49]:
arr.shape

(25,)

In [50]:
ranarr.shape

(10,)

In [51]:
arr = arr.reshape(5,5)

In [52]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape

(5, 5)

## dtype
* returns the datatype of the array
* It is also a attribute.
    

In [54]:
arr.dtype


dtype('int32')