# Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Accessing the elements from the array

In [4]:
arr[7]

7

## Array Slicing
* Used to access some part of array.
##### <p style="color: blue;">Note that in below example, the upper limit is excluded.</p>

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
# Accessing elements from middle to end.
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
# Accessing every second element in array
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

## Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:
##### <p style="color: green;">Broadcasting means, setting a value with index range.</p>

In [14]:
arr[0:5] = 100

In [15]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Important Note on Slice.

In [20]:
slice_of_arr = arr[:6]

In [21]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
# changing the value of slice_of_arr through Broadcastng.
slice_of_arr[0:6] = 99

In [23]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

<p style = "color: green;">Now, note the values in original array i.e. "arr" has also changed.</p>

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### This is because, `slice_of_arr` was not a separate array. It was the `view/reference` of `arr`. 
#### Numpy uses this feature to avoid memory problems.


### To get a copy we have to specify it explicitly.

In [25]:
arr_copy = arr.copy()

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_copy[:] = 100 

In [29]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [30]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2-D Array.

In [32]:
arr_2d = np.array([[5,10,15], [20,25,30], [50,60,70]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [50, 60, 70]])

In [34]:
# Accessing whole row.
arr_2d[0]

array([ 5, 10, 15])

#### 1. Using double bracket notation

In [36]:
arr_2d[1][1]

25

In [37]:
arr_2d[2][2]

70

#### 2. Using comma and single bracket notation

In [38]:
arr_2d[1,2]

30

the first number represents row and second one represents column.

### 2-D array slicing

In [40]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr_2d[:, :1]

array([[ 5],
       [20],
       [50]])

In [42]:
arr_2d[1:, :]

array([[20, 25, 30],
       [50, 60, 70]])

In [43]:
arr_2d[2:, :]

array([[50, 60, 70]])

## Conditional Selection

In [44]:
arr = np.arange(11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Using a `comparision operator` on an array will return the boolean array.

In [46]:
bool_arr = arr > 5

In [47]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [48]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

##### Doing it directly

In [51]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

##### Grabbing all the elements that are less than 3.

In [50]:
arr[arr<3]

array([0, 1, 2])

## Practice


In [52]:
arr_2d = np.arange(50).reshape(5,10)

In [53]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
arr_2d[1:4, 2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [60]:
arr_2d[arr_2d>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])